# Generated by Django 5.2.8 on 2026-01-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytask_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completed_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(blank=True, max_length=50, null=True)),
                ('tag_name', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
