# Generated by Django 5.2.8 on 2025-12-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytask_app', '0002_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='piority_level',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=6),
        ),
    ]
