# Generated by Django 5.2.8 on 2026-01-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytask_app', '0006_remainder_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='remainder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
